name: 'ECA Config'
type: module
description: 'Config events.'
core_version_requirement: ^11.2
package: ECA
dependencies:
  - eca:eca

# Information added by Drupal.org packaging script on 2025-11-05
version: '3.0.7'
project: 'eca'
datestamp: 1762344438
